In [1]:
import numpy as np

In [3]:
''' You are given a space separated list of numbers.
Your task is to print a reversed Numpy array with the element type float.
Input Format
A single line of input containing space separated numbers.
Output Format
Print the reverse NumPy array with type float.'''

arr = list(map(int,input("Enter Array:- ").split()))
arr.reverse()
out = np.array(arr,dtype = float)
print(out)

[-10.  -8.   3.   2.   1.]


In [4]:
'''You are given a space separated list of nine integers. Your task is to convert this list into 3x3 numpy array.
Input Format
A single line of input containing space separated integers.
Output Format
Print the 3x3 numpy array.'''

arr = list(map(int,input().split()))
arr = np.array(arr)
arr = arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
'''
You are given a space separated list of nine integers. Your task is to convert this list into 3x3 numpy array.
Input Format
A single line of input containing space separated integers.
Output Format
Print the 3x3 numpy array.'''
dim = list(map(int,input().split()))
print(np.identity(dim[0]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
'''
Input Format
The first line contains two space separated integers, N and M.
The next N lines contains M space separated integers of array A.
The following N lines contains M space separated integers of array B.
Output Format
Print the result of each operation in the given order under Task
'''
s_e = list(map(int,input().split()))
m1 = []
m2 = []
for i in range(s_e[0]):
    m1.append(list(map(int,input().split())))
    m2.append(list(map(int,input().split())))
print(m1,m2)
out1 = np.array(m1)
out2 = np.array(m2)
ad = np.add(out1,out2)
sub = np.subtract(out1,out2)
mul = np.multiply(out1,out2)
floor_div = np.floor_divide(out1,out2)
norm_div = np.divide(out1,out2)
"mod_div = np.divmod(out,out2)"
powe = np.power(out1, out2)
powe1 = np.float_power(out1,out2)
print(f"ADD: {ad}\nSubtract: {sub}\nMultiply: {mul}\nFloor_Divide: {floor_div}\nNormal_Division: {norm_div}\nPower: {powe}\nFloat_Power: {powe1}")

[[1, 2, 3, 4]] [[5, 6, 7, 8]]
ADD: [[ 6  8 10 12]]
Subtract: [[-4 -4 -4 -4]]
Multiply: [[ 5 12 21 32]]
Floor_Divide: [[0 0 0 0]]
Normal_Division: [[0.2        0.33333333 0.42857143 0.5       ]]
Power: [[    1    64  2187 65536]]
Float_Power: [[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]]
