In [1]:
import numpy as np

In [3]:
''' You are given a space separated list of numbers.
Your task is to print a reversed Numpy array with the element type float.
Input Format
A single line of input containing space separated numbers.
Output Format
Print the reverse NumPy array with type float.'''

arr = list(map(int,input("Enter Array:- ").split()))
arr.reverse()
out = np.array(arr,dtype = float)
print(out)

[-10.  -8.   3.   2.   1.]


In [4]:
'''You are given a space separated list of nine integers. Your task is to convert this list into 3x3 numpy array.
Input Format
A single line of input containing space separated integers.
Output Format
Print the 3x3 numpy array.'''

arr = list(map(int,input().split()))
arr = np.array(arr)
arr = arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
'''
You are given a space separated list of nine integers. Your task is to convert this list into 3x3 numpy array.
Input Format
A single line of input containing space separated integers.
Output Format
Print the 3x3 numpy array.'''
dim = list(map(int,input().split()))
print(np.identity(dim[0]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
